import { Product } from './types';

// DAYLI® product lineup — 6 precision nutrition superblends
// Each product targets a specific demographic with tailored formulations

export const DAYLI_PRODUCTS: Product[] = [
    {
        id: 'dayli-kids',
        name: 'DAYLI® KIDS',
        slug: 'dayli-kids',
        tagline: 'Smarter Growth. Stronger Immunity. Sharper Focus.',
        description: 'All-In-One Superblend for growing bodies and developing brains.',
        long_description: 'Built for growing bodies and developing brains, DAYLI Kids delivers essential protein, fiber, nano vitamins & minerals, postbiotics, electrolytes, and cognitive nutrients in the right balance — not a generic adult mix diluted for children. Precision Nutrients™ engineered for maximum customization, superior biology, cost-effectiveness and sustainability.',
        category: 'Core Nutrition',
        target_group: 'Children (5–14 YRS)',
        price_subscription: 49.00,
        price_one_time: 75.00,
        badge: 'Kids 5–14 YRS',
        is_featured: true,
        layers: ['L1: Macros', 'L2: Micros', 'L3: Amino Acids', 'L4: Biotics'],
        benefits: ['Height & muscle growth', 'Iron & micronutrient sufficiency', 'Gut health & immunity', 'Brain development & focus', 'Daily energy without sugar spikes'],
        images: ['/images/products/dayli_kids.png'],
    },
    {
        id: 'dayli-women',
        name: 'DAYLI® WOMEN',
        slug: 'dayli-women',
        tagline: 'Energy That Lasts. Immunity That Protects. Strength That Sustains.',
        description: 'All-In-One Superblend for women who carry everything — and still show up strong.',
        long_description: 'DAYLI Women is engineered for women balancing career, family, stress, and recovery. It combines protein, collagen building blocks, postbiotics, essential micronutrients, and cognitive support compounds. Precision Nutrients™ — modular building blocks of nutrition engineered for maximum customization and superior biology.',
        category: 'Core Nutrition',
        target_group: 'Women (21–50 YRS)',
        price_subscription: 49.00,
        price_one_time: 75.00,
        badge: 'Women 21–50 YRS',
        is_featured: true,
        layers: ['L1: Macros', 'L2: Micros', 'L3: Amino Acids', 'L4: Biotics', 'L5: Growth Factors'],
        benefits: ['Sustained daily energy', 'Stress & burnout resilience', 'Gut & immunity health', 'Collagen & structural support', 'Cognitive clarity'],
        images: ['/images/products/dayli_women.png'],
    },
    {
        id: 'dayli-gym-freaks',
        name: 'DAYLI® GYM FREAKS',
        slug: 'dayli-gym-freaks',
        tagline: 'Build. Recover. Perform. Repeat.',
        description: 'All-In-One Superblend — not just nutrients, a full performance architecture.',
        long_description: 'DAYLI Gym Freaks is a complete daily support system with high-dose protein & fiber, EAAs, BCAAs, electrolytes, nano minerals, postbiotics, and performance compounds. Precision Nutrients™ — modular building blocks of nutrition engineered for maximum customization and superior biology.',
        category: 'Performance',
        target_group: 'Gym Freaks (21–50 YRS)',
        price_subscription: 49.00,
        price_one_time: 75.00,
        badge: 'Gym Freaks 21–50 YRS',
        is_featured: true,
        layers: ['L1: Macros', 'L2: Micros', 'L3: Amino Acids', 'L4: Biotics', 'L5: Growth Factors'],
        benefits: ['Lean muscle building', 'Recovery & endurance', 'Electrolyte balance', 'Metabolic efficiency', 'Focus & performance'],
        images: ['/images/products/dayli_gym_freaks.png'],
    },
    {
        id: 'dayli-seniors',
        name: 'DAYLI® SENIORS',
        slug: 'dayli-seniors',
        tagline: 'Vitality. Resilience. Graceful Strength.',
        description: 'All-In-One Superblend for active ageing and sustained vitality.',
        long_description: 'DAYLI Seniors is precision-formulated for adults 50+ who want to maintain bone density, cognitive sharpness, cardiovascular health, and daily energy. Features bioavailable calcium, vitamin D3/K2, CoQ10, and advanced postbiotics for gut-immune optimization. Precision Nutrients™ engineered for superior biology.',
        category: 'Core Nutrition',
        target_group: 'Seniors (50+)',
        price_subscription: 49.00,
        price_one_time: 75.00,
        badge: 'Seniors 50+',
        is_featured: true,
        layers: ['L1: Macros', 'L2: Micros', 'L3: Amino Acids', 'L4: Biotics', 'L5: Growth Factors'],
        benefits: ['Bone & joint strength', 'Cardiovascular support', 'Cognitive sharpness', 'Immune resilience', 'Sustained daily energy'],
        images: ['/images/products/dayli_seniors.png'],
    },
    {
        id: 'dayli-men',
        name: 'DAYLI® MEN',
        slug: 'dayli-men',
        tagline: 'Peak Performance. Total Balance. Everyday Strength.',
        description: 'All-In-One Superblend for men who demand more from their nutrition.',
        long_description: 'DAYLI Men delivers a precision-calibrated stack of protein, performance amino acids, nano minerals, adaptogenic compounds, and gut health support tailored to male biology. Supports testosterone balance, lean mass maintenance, stress resilience, and cardiovascular health. Precision Nutrients™ engineered for superior biology.',
        category: 'Core Nutrition',
        target_group: 'Men (21–50 YRS)',
        price_subscription: 49.00,
        price_one_time: 75.00,
        badge: 'Men 21–50 YRS',
        is_featured: true,
        layers: ['L1: Macros', 'L2: Micros', 'L3: Amino Acids', 'L4: Biotics', 'L5: Growth Factors'],
        benefits: ['Lean muscle support', 'Hormonal balance', 'Stress & recovery', 'Heart health', 'Mental clarity & focus'],
        images: ['/images/products/dayli_men.png'],
    },
    {
        id: 'dayli-girls',
        name: 'DAYLI® GIRLS',
        slug: 'dayli-girls',
        tagline: 'Confidence. Clarity. Hormone Balance.',
        description: 'All-In-One Superblend built for stronger bodies and sharper minds during critical years.',
        long_description: 'DAYLI Girls is designed for teenage girls navigating growth, hormonal shifts, academic pressure, and lifestyle stress. It supports iron balance, energy metabolism, skin health, gut resilience, and cognitive performance. Precision Nutrients™ — modular building blocks engineered for maximum customization and superior biology.',
        category: 'Core Nutrition',
        target_group: 'Girls (12–20 YRS)',
        price_subscription: 49.00,
        price_one_time: 75.00,
        badge: 'Girls 12–20 YRS',
        is_featured: true,
        layers: ['L1: Macros', 'L2: Micros', 'L3: Amino Acids', 'L4: Biotics'],
        benefits: ['Iron & hemoglobin balance', 'Hormonal stability', 'Energy & stamina', 'Skin & collagen building', 'Focus & emotional resilience'],
        images: ['/images/products/dayli_girls.png'],
    },
];

// Product color mapping for UI theming
export const DAYLI_PRODUCT_COLORS: Record<string, { bg: string; text: string; accent: string; border: string }> = {
    'dayli-kids': { bg: 'bg-amber-50', text: 'text-amber-700', accent: 'bg-amber-500', border: 'border-amber-200' },
    'dayli-women': { bg: 'bg-red-50', text: 'text-red-700', accent: 'bg-red-500', border: 'border-red-200' },
    'dayli-gym-freaks': { bg: 'bg-orange-50', text: 'text-orange-700', accent: 'bg-orange-500', border: 'border-orange-200' },
    'dayli-seniors': { bg: 'bg-teal-50', text: 'text-teal-700', accent: 'bg-teal-500', border: 'border-teal-200' },
    'dayli-men': { bg: 'bg-blue-50', text: 'text-blue-700', accent: 'bg-blue-500', border: 'border-blue-200' },
    'dayli-girls': { bg: 'bg-purple-50', text: 'text-purple-700', accent: 'bg-purple-500', border: 'border-purple-200' },
};
